[package]
name = "visbile_private-2015"
version = "0.1.0"
authors = ["Kreedzt <zhaozisong1@live.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
